// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace MarsCompetitionReqnroll.Net8Selenium.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Certification Management")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class CertificationManagementFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Certification Management", "  As a logged-in user\r\n  I want to manage certification records\r\n  So that I can " +
                "add, edit, validate, and delete certifications", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CertificationManagement.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
 #line hidden
#line 7
  await testRunner.GivenAsync("I navigate to the Mars portal login page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.WhenAsync("I enter valid username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
  await testRunner.AndAsync("I click on the login button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
  await testRunner.ThenAsync("I should be redirected to the dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
  await testRunner.AndAsync("the user navigates to the Profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
  await testRunner.AndAsync("the user opens the Certifications section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CertificationManagement.feature.ndjson", 12);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_01 - Create new certification")]
        [global::NUnit.Framework.CategoryAttribute("Order(1)")]
        [global::NUnit.Framework.CategoryAttribute("TC_01")]
        [global::NUnit.Framework.CategoryAttribute("Create")]
        public async global::System.Threading.Tasks.Task TC_01_CreateNewCertification()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(1)",
                    "TC_01",
                    "Create"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_01 - Create new certification", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.WhenAsync("the user creates a certification using test data \"TC_01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("a success notification should be displayed for certification \"TC_01\" with action " +
                        "\"added\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_02 - Create duplicate certification")]
        [global::NUnit.Framework.CategoryAttribute("Order(2)")]
        [global::NUnit.Framework.CategoryAttribute("TC_02")]
        [global::NUnit.Framework.CategoryAttribute("Create")]
        [global::NUnit.Framework.CategoryAttribute("Duplicate")]
        public async global::System.Threading.Tasks.Task TC_02_CreateDuplicateCertification()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(2)",
                    "TC_02",
                    "Create",
                    "Duplicate"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_02 - Create duplicate certification", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync("the certification record exists using test data \"TC_01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.WhenAsync("the user creates a certification using test data \"TC_02\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("an error notification should be displayed with message key \"ALREADY_EXISTS_CERTIF" +
                        "ICATION_ERROR\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_03 - Create certification with same name and from but different year")]
        [global::NUnit.Framework.CategoryAttribute("Order(3)")]
        [global::NUnit.Framework.CategoryAttribute("TC_03")]
        [global::NUnit.Framework.CategoryAttribute("Create")]
        [global::NUnit.Framework.CategoryAttribute("Duplicate")]
        public async global::System.Threading.Tasks.Task TC_03_CreateCertificationWithSameNameAndFromButDifferentYear()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(3)",
                    "TC_03",
                    "Create",
                    "Duplicate"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_03 - Create certification with same name and from but different year", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.WhenAsync("the user creates a certification using test data \"TC_03\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("an error notification should be displayed with message key \"DUPLICATE_CERTIFICATI" +
                        "ON_ERROR\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_04 - Edit existing certification name")]
        [global::NUnit.Framework.CategoryAttribute("Order(4)")]
        [global::NUnit.Framework.CategoryAttribute("TC_04")]
        [global::NUnit.Framework.CategoryAttribute("Edit")]
        public async global::System.Threading.Tasks.Task TC_04_EditExistingCertificationName()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(4)",
                    "TC_04",
                    "Edit"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_04 - Edit existing certification name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 37
    await testRunner.GivenAsync("the certification record exists using test data \"TC_01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
    await testRunner.WhenAsync("the user updates the certification name using test data \"TC_04\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("a success notification should be displayed for certification \"TC_04\" with action " +
                        "\"updated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_05 - Create certification using numeric values")]
        [global::NUnit.Framework.CategoryAttribute("Order(5)")]
        [global::NUnit.Framework.CategoryAttribute("TC_05")]
        [global::NUnit.Framework.CategoryAttribute("Create")]
        public async global::System.Threading.Tasks.Task TC_05_CreateCertificationUsingNumericValues()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(5)",
                    "TC_05",
                    "Create"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_05 - Create certification using numeric values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.WhenAsync("the user creates a certification using test data \"TC_05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("a success notification should be displayed for certification \"TC_05\" with action " +
                        "\"added\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_06 - Delete certification created with numeric values")]
        [global::NUnit.Framework.CategoryAttribute("Order(6)")]
        [global::NUnit.Framework.CategoryAttribute("TC_06")]
        [global::NUnit.Framework.CategoryAttribute("Delete")]
        public async global::System.Threading.Tasks.Task TC_06_DeleteCertificationCreatedWithNumericValues()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(6)",
                    "TC_06",
                    "Delete"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_06 - Delete certification created with numeric values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 50
    await testRunner.GivenAsync("the certification record exists using test data \"TC_05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
    await testRunner.WhenAsync("the user deletes the certification using test data \"TC_05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("a success notification should be displayed for certification \"TC_05\" with action " +
                        "\"deleted\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_07 - Create certification with special characters")]
        [global::NUnit.Framework.CategoryAttribute("Order(7)")]
        [global::NUnit.Framework.CategoryAttribute("TC_07")]
        [global::NUnit.Framework.CategoryAttribute("Create")]
        public async global::System.Threading.Tasks.Task TC_07_CreateCertificationWithSpecialCharacters()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(7)",
                    "TC_07",
                    "Create"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_07 - Create certification with special characters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 57
    await testRunner.WhenAsync("the user creates a certification using test data \"TC_07\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("a success notification should be displayed for certification \"TC_07\" with action " +
                        "\"added\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_08 - Create certification with very long text values")]
        [global::NUnit.Framework.CategoryAttribute("Order(8)")]
        [global::NUnit.Framework.CategoryAttribute("TC_08")]
        [global::NUnit.Framework.CategoryAttribute("Boundary")]
        public async global::System.Threading.Tasks.Task TC_08_CreateCertificationWithVeryLongTextValues()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(8)",
                    "TC_08",
                    "Boundary"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_08 - Create certification with very long text values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.WhenAsync("the user creates a certification using test data \"TC_08\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("a success notification should be displayed for certification \"TC_08\" with action " +
                        "\"added\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_010 - Empty field validation during certification creation")]
        [global::NUnit.Framework.CategoryAttribute("Order(9)")]
        [global::NUnit.Framework.CategoryAttribute("TC_010")]
        [global::NUnit.Framework.CategoryAttribute("Validation")]
        [global::NUnit.Framework.CategoryAttribute("Negative")]
        public async global::System.Threading.Tasks.Task TC_010_EmptyFieldValidationDuringCertificationCreation()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(9)",
                    "TC_010",
                    "Validation",
                    "Negative"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_010 - Empty field validation during certification creation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 69
    await testRunner.WhenAsync("the user attempts to create a certification using test data \"TC_010\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
    await testRunner.ThenAsync("an error notification should be displayed with message key \"MANDATORY_FIELDS_ERRO" +
                        "R\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_011 - Cleanup all certifications created during test execution")]
        [global::NUnit.Framework.CategoryAttribute("Order(10)")]
        [global::NUnit.Framework.CategoryAttribute("TC_011")]
        [global::NUnit.Framework.CategoryAttribute("Cleanup")]
        public async global::System.Threading.Tasks.Task TC_011_CleanupAllCertificationsCreatedDuringTestExecution()
        {
            string[] tagsOfScenario = new string[] {
                    "Order(10)",
                    "TC_011",
                    "Cleanup"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_011 - Cleanup all certifications created during test execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await this.FeatureBackgroundAsync();
#line hidden
#line 75
    await testRunner.WhenAsync("the user deletes all certifications created during this test run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
    await testRunner.ThenAsync("no test certification records should exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
